# Generated by Django 6.0.3 on 2026-06-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.JSONField(),
        ),
    ]
