# Generated by Django 6.0.3 on 2026-06-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_new_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(),
        ),
    ]
