# Generated by Django 6.0.3 on 2026-08-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_new_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_list',
        ),
        migrations.RemoveField(
            model_name='project',
            name='paragraph_list',
        ),
        migrations.AddField(
            model_name='project',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='paragraph_1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='paragraph_2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
