# Generated by Django 6.0.3 on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_project_image_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="paragraph_2",
            field=models.TextField(blank=True, default=""),
        ),
    ]
